apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: mycluster
  region: ap-southeast-1
 
nodeGroups:
  - name: node-group-1
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 8
    ssh:
      allow: true
