apiVersion: v1
kind: Pod
metadata:
  name: task-pv-ebs
spec:
  volumes:
    - name: ebs-claim-vol
      persistentVolumeClaim:
        claimName: ebs-claim
  containers:
    - name: ebs-claim-vol
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ebs-claim-vol
